### ISSUE TITLE
can't compile on ubuntu 16.04

### ISSUE THREAD

**Issue by gritsulyak** [Nable80/wwwconf#1]
wwwconf/wwwconf$ make
g++ -m32 -O2 -fomit-frame-pointer -fno-exceptions -Wall -Wextra -Werror -Wfatal-errors -pedantic -c statfs.cpp
statfs.cpp:2:21: fatal error: sys/vfs.h: Нет такого файла или каталога
compilation terminated.
Makefile:26: ошибка выполнения рецепта для цели «statfs.o»
make: *** [statfs.o] Ошибка 1

**Comment by Nable80** [comment]
Did you install main development package (libc6-dev-**i386** or libc6-dev:i386)? Please note that only 32-bit little-endian targets are supported at the moment due to bad decisions of original authors.

**Comment by gritsulyak** [comment]
yes, fixed also with 
sudo apt-get install g++-multilib

compiling done.
